import hre from "hardhat";
import { expect } from "chai";
import { generateProof } from "../scripts/generateProof.js";

describe("Groth16Verifier Direct Test", function () {
  let verifier;

  before(async function () {
    const Verifier = await hre.ethers.getContractFactory("Groth16Verifier");
    verifier = await Verifier.deploy();
    await verifier.waitForDeployment();
  });

  it("should verify a valid proof generated by snarkjs", async function () {
    // Generate proof with snarkjs
    const { solidityCalldata } = await generateProof({
      rawPrediction: 750,
      salt: 123,
      threshold: 500,
    });

    const { pA, pB, pC, pubSignals } = solidityCalldata;

    console.log("\n[TEST] Verifying proof directly against Groth16Verifier:");
    console.log("  pA:", pA);
    console.log("  pB:", pB);
    console.log("  pC:", pC);
    console.log("  pubSignals:", pubSignals);

    // Call verifyProof directly
    const isValid = await verifier.verifyProof(pA, pB, pC, pubSignals);
    console.log("  Result:", isValid ? "✓ VALID" : "✗ INVALID");

    expect(isValid).to.be.true;
  });
});
