// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title MockVerifier
 * @notice Configurable mock of the Groth16 Verifier contract, used ONLY in tests.
 *
 * This allows Oracle.sol unit tests to run without requiring the full Circom
 * circuit compilation pipeline (which downloads ~54MB of ptau data and runs
 * several minutes of setup). Tests can control whether proofs pass or fail.
 *
 * DO NOT deploy this contract to mainnet or testnet.
 * The real Verifier.sol (generated by snarkjs) must be used in production.
 */
contract MockVerifier {
    bool private _returnValue;

    /**
     * @param returnValue If true, verifyProof() always returns true (valid proof).
     *                    If false, verifyProof() always returns false (invalid proof).
     */
    constructor(bool returnValue) {
        _returnValue = returnValue;
    }

    /**
     * @dev Mock implementation of the Groth16 verifyProof interface.
     *      Ignores all proof components and returns the configured boolean.
     *
     * Signature matches contracts/Verifier.sol and IVerifier in Oracle.sol.
     */
    function verifyProof(
        uint[2] calldata,
        uint[2][2] calldata,
        uint[2] calldata,
        uint[3] calldata
    ) external view returns (bool) {
        return _returnValue;
    }

    /**
     * @dev Allows tests to change the mock's return value mid-test.
     */
    function setReturnValue(bool newValue) external {
        _returnValue = newValue;
    }
}
