// scripts/deploy.js
// ─────────────────────────────────────────────────────────────────────────────
// Hardhat deployment script for ZK Oracle on Rootstock.
//
// Deploys two contracts in order:
//   1. Verifier.sol  — Groth16 proof verifier (generated by npm run compile:circuit)
//   2. Oracle.sol    — Main oracle contract (receives verifier address in constructor)
//
// Usage:
//   npm run deploy:local     # Local Hardhat node
//   npm run deploy:testnet   # Rootstock testnet (chainId 31)
//   npm run deploy:mainnet   # Rootstock mainnet (chainId 30)
//
// Prerequisites:
//   1. npm run compile:circuit    (generates real Verifier.sol)
//   2. npm run compile:contracts  (compiles Solidity artifacts)
//   3. .env with PRIVATE_KEY      (funded wallet for testnet/mainnet)
//      Get tRBTC from: https://faucet.rootstock.io
// ─────────────────────────────────────────────────────────────────────────────

import hre from "hardhat";
import { writeFileSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

async function main() {
  const { ethers, network } = hre;
  const [deployer] = await ethers.getSigners();

  console.log("");
  console.log("╔════════════════════════════════════════════╗");
  console.log("║  Rootstock ZK Oracle — Deployment Script   ║");
  console.log("╚════════════════════════════════════════════╝");
  console.log("");
  console.log(`Network:   ${network.name} (chainId: ${network.config.chainId})`);
  console.log(`Deployer:  ${deployer.address}`);

  const balance = await ethers.provider.getBalance(deployer.address);
  console.log(`Balance:   ${ethers.formatEther(balance)} RBTC`);

  if (balance === 0n && network.name !== "hardhat") {
    console.warn("\nWARNING: Deployer balance is 0.");
    if (network.name === "rskTestnet") {
      console.warn("Get tRBTC from: https://faucet.rootstock.io");
    }
  }

  // ── Step 1: Deploy Verifier.sol ───────────────────────────────────────────
  console.log("\n─────────────────────────────────────────────");
  console.log("Step 1/2: Deploying Verifier.sol");
  console.log("─────────────────────────────────────────────");
  console.log("Note: Verifier.sol must be the REAL verifier generated by");
  console.log("      npm run compile:circuit (not the stub).");

  const VerifierFactory = await ethers.getContractFactory("Verifier");
  const verifierDeploy = await VerifierFactory.deploy();

  console.log(`  Transaction hash: ${verifierDeploy.deploymentTransaction()?.hash}`);
  console.log("  Waiting for deployment...");

  await verifierDeploy.waitForDeployment();
  const verifierAddress = await verifierDeploy.getAddress();

  console.log(`  Verifier deployed: ${verifierAddress}`);

  // ── Step 2: Deploy Oracle.sol ─────────────────────────────────────────────
  console.log("\n─────────────────────────────────────────────");
  console.log("Step 2/2: Deploying Oracle.sol");
  console.log("─────────────────────────────────────────────");

  const OracleFactory = await ethers.getContractFactory("Oracle");
  const oracleDeploy = await OracleFactory.deploy(verifierAddress);

  console.log(`  Transaction hash: ${oracleDeploy.deploymentTransaction()?.hash}`);
  console.log("  Waiting for deployment...");

  await oracleDeploy.waitForDeployment();
  const oracleAddress = await oracleDeploy.getAddress();

  console.log(`  Oracle deployed: ${oracleAddress}`);

  // ── Step 3: Verify linkage ────────────────────────────────────────────────
  console.log("\n─────────────────────────────────────────────");
  console.log("Verifying contract linkage...");
  const oracle = await ethers.getContractAt("Oracle", oracleAddress);
  const linkedVerifier = await oracle.verifier();

  if (linkedVerifier.toLowerCase() !== verifierAddress.toLowerCase()) {
    throw new Error(
      `Verifier address mismatch!\n` +
      `  Expected: ${verifierAddress}\n` +
      `  Got:      ${linkedVerifier}`
    );
  }
  console.log(`  Oracle.verifier() == ${linkedVerifier} ✓`);

  // ── Step 4: Save deployment info ──────────────────────────────────────────
  const blockNumber = await ethers.provider.getBlockNumber();

  const deployment = {
    network:     network.name,
    chainId:     network.config.chainId,
    deployer:    deployer.address,
    verifier:    verifierAddress,
    oracle:      oracleAddress,
    timestamp:   new Date().toISOString(),
    blockNumber: blockNumber,
  };

  const deployPath = path.join(__dirname, "..", "deployments.json");
  writeFileSync(deployPath, JSON.stringify(deployment, null, 2));

  // ── Summary ───────────────────────────────────────────────────────────────
  console.log("");
  console.log("╔════════════════════════════════════════════╗");
  console.log("║  Deployment Complete!                      ║");
  console.log("╚════════════════════════════════════════════╝");
  console.log("");
  console.log("Addresses:");
  console.log(`  Verifier: ${verifierAddress}`);
  console.log(`  Oracle:   ${oracleAddress}`);
  console.log("");
  console.log(`Saved to: deployments.json`);

  // Rootstock explorer links
  const explorerBase =
    network.name === "rskTestnet"  ? "https://explorer.testnet.rootstock.io" :
    network.name === "rskMainnet"  ? "https://explorer.rootstock.io"         : null;

  if (explorerBase) {
    console.log("");
    console.log("Explorer links:");
    console.log(`  Verifier: ${explorerBase}/address/${verifierAddress}`);
    console.log(`  Oracle:   ${explorerBase}/address/${oracleAddress}`);
  }

  console.log("");
  console.log("Next steps:");
  console.log("  1. Copy addresses to .env: ORACLE_ADDRESS and VERIFIER_ADDRESS");
  console.log("  2. Run the agent: node agent/index.js");
  console.log(`  3. The agent will predict → prove → submit to Oracle at ${oracleAddress}`);
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("\nDeployment failed:", err.message);
    process.exit(1);
  });
