// scripts/generateProof.js
// ─────────────────────────────────────────────────────────────────────────────
// Generate and verify a Groth16 ZK proof for the PredictionProof circuit.
//
// This module handles the full snarkjs workflow:
//   1. Validate inputs (range check)
//   2. Generate Groth16 proof (witness computation + prover)
//   3. Verify proof off-chain (sanity check before costly on-chain submission)
//   4. Format proof as Solidity calldata for Oracle.sol
//
// Used by:
//   agent/index.js        — automated pipeline
//   CLI:                  — node scripts/generateProof.js --prediction 750 --threshold 500
//
// Prerequisites:
//   npm run compile:circuit  (compiles circuit, generates .wasm and .zkey files)
// ─────────────────────────────────────────────────────────────────────────────

import * as snarkjs from "snarkjs";
import { readFileSync, existsSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

// ── Artifact paths (generated by npm run compile:circuit) ─────────────────────
const WASM_PATH  = path.join(ROOT, "circuits", "prediction_js", "prediction.wasm");
const ZKEY_PATH  = path.join(ROOT, "circuits", "prediction_final.zkey");
const VKEY_PATH  = path.join(ROOT, "circuits", "verification_key.json");

/**
 * Generate a Groth16 ZK proof for the PredictionProof circuit.
 *
 * The proof cryptographically demonstrates that:
 *   1. A value raw_prediction exists in [0, 10000]
 *   2. predicted_yield (public output) equals raw_prediction
 *   3. is_above_threshold (public output) correctly reflects raw_prediction >= threshold
 *
 * Without revealing raw_prediction or salt to anyone.
 *
 * @param {Object} params
 * @param {number} params.rawPrediction  Private: AI model output (0-10000 basis points)
 * @param {number} params.salt           Private: random nonce (any large integer)
 * @param {number} params.threshold      Public: comparison threshold (e.g., 500 = 5%)
 *
 * @returns {Promise<{
 *   proof: Object,            Raw snarkjs proof object
 *   publicSignals: string[],  Public signals: [predicted_yield, is_above_threshold, threshold]
 *   solidityCalldata: {
 *     pA: string[],           Proof A for Solidity call
 *     pB: string[][],         Proof B for Solidity call
 *     pC: string[],           Proof C for Solidity call
 *     pubSignals: string[],   Public signals for Solidity call
 *   },
 *   callDataRaw: string       Raw calldata string from snarkjs
 * }>}
 */
export async function generateProof({ rawPrediction, salt, threshold }) {
  // ── Input validation ───────────────────────────────────────────────────────
  if (!Number.isInteger(rawPrediction) || rawPrediction < 0 || rawPrediction > 10000) {
    throw new Error(
      `rawPrediction must be an integer in [0, 10000], got: ${rawPrediction}`
    );
  }
  if (!Number.isInteger(threshold) || threshold < 0 || threshold > 10000) {
    throw new Error(
      `threshold must be an integer in [0, 10000], got: ${threshold}`
    );
  }

  // ── Check compiled artifacts ───────────────────────────────────────────────
  if (!existsSync(WASM_PATH)) {
    throw new Error(
      `Circuit WASM not found: ${WASM_PATH}\n` +
      `Run: npm run compile:circuit\n` +
      `(This downloads the ptau file and compiles the Circom circuit)`
    );
  }
  if (!existsSync(ZKEY_PATH)) {
    throw new Error(
      `ZKey not found: ${ZKEY_PATH}\n` +
      `Run: npm run compile:circuit`
    );
  }
  if (!existsSync(VKEY_PATH)) {
    throw new Error(
      `Verification key not found: ${VKEY_PATH}\n` +
      `Run: npm run compile:circuit`
    );
  }

  // ── Build circuit input ────────────────────────────────────────────────────
  // CRITICAL: Object keys MUST exactly match the circuit's signal names.
  // See circuits/prediction.circom:
  //   signal input raw_prediction;  ← must match
  //   signal input salt;            ← must match
  //   signal input threshold;       ← must match (public)
  //
  // snarkjs requires string values (it internally uses BigInt arithmetic).
  const input = {
    raw_prediction: rawPrediction.toString(),
    salt: salt.toString(),
    threshold: threshold.toString(),
  };

  console.log("  [ZK] Generating Groth16 proof...");
  console.log(`  [ZK] Public input: threshold=${threshold} bps`);
  console.log("  [ZK] Private inputs: hidden (raw_prediction, salt)");

  // ── Generate proof ─────────────────────────────────────────────────────────
  // snarkjs.groth16.fullProve() performs two steps internally:
  //   1. Witness generation: uses the .wasm file to compute all circuit signals
  //   2. Proof generation: uses the .zkey file to create the Groth16 proof
  //
  // Returns:
  //   proof         = { pi_a, pi_b, pi_c, protocol: "groth16", curve: "bn128" }
  //   publicSignals = string[] in order: [predicted_yield, is_above_threshold, threshold]
  //
  // Note: outputs (predicted_yield, is_above_threshold) come BEFORE public inputs (threshold)
  // in the publicSignals array. This ordering is determined by snarkjs.
  const { proof, publicSignals } = await snarkjs.groth16.fullProve(
    input,
    WASM_PATH,
    ZKEY_PATH
  );

  console.log("  [ZK] Proof generated successfully");
  console.log(`  [ZK] predicted_yield:     ${publicSignals[0]} bps`);
  console.log(`  [ZK] is_above_threshold:  ${publicSignals[1]} (${publicSignals[1] === "1" ? "YES" : "NO"})`);
  console.log(`  [ZK] threshold:           ${publicSignals[2]} bps`);

  // ── Off-chain verification ─────────────────────────────────────────────────
  // Verify the proof locally before submitting on-chain.
  // This catches invalid proofs early and saves gas on failed transactions.
  console.log("  [ZK] Verifying proof off-chain...");
  const vKey = JSON.parse(readFileSync(VKEY_PATH, "utf-8"));
  const isValid = await snarkjs.groth16.verify(vKey, publicSignals, proof);

  if (!isValid) {
    throw new Error(
      "Off-chain proof verification FAILED.\n" +
      "This should not happen with valid inputs — check circuit constraints."
    );
  }
  console.log("  [ZK] Off-chain verification: PASSED");

  // ── Format for Solidity ────────────────────────────────────────────────────
  // exportSolidityCallData formats the proof as Solidity function arguments.
  // Output format: "[pA_x, pA_y],[[pB_x1,pB_x2],[pB_y1,pB_y2]],[pC_x, pC_y],[s0,s1,s2,...]"
  const callDataRaw = await snarkjs.groth16.exportSolidityCallData(proof, publicSignals);
  const solidityCalldata = parseCallData(callDataRaw);

  // DEBUG: Show what will be sent to contract
  if (process.env.DEBUG_PROOF) {
    debugProofData(
      solidityCalldata.pA,
      solidityCalldata.pB,
      solidityCalldata.pC,
      solidityCalldata.pubSignals,
      publicSignals
    );
  }

  return {
    proof,
    publicSignals,
    solidityCalldata,
    callDataRaw,
  };
}

/**
 * Parse the raw calldata string from snarkjs into structured arrays.
 *
 * snarkjs exportSolidityCallData returns a comma-separated bracket string:
 *   [pA_x, pA_y], [[pB_x1,pB_x2],[pB_y1,pB_y2]], [pC_x, pC_y], [s0, s1, s2]
 *
 * We parse this into typed arrays compatible with ethers.js contract calls.
 * All numeric values are converted to strings that ethers.js v6 can parse.
 *
 * @param {string} callDataRaw Raw string from snarkjs
 * @returns {{ pA: string[], pB: string[][], pC: string[], pubSignals: string[] }}
 */
function parseCallData(callDataRaw) {
  // Wrap in outer array brackets for JSON parsing
  const cleanedStr = `[${callDataRaw}]`;

  let parsed;
  try {
    parsed = JSON.parse(cleanedStr);
  } catch (err) {
    throw new Error(`Failed to parse snarkjs calldata: ${err.message}\nRaw: ${callDataRaw}`);
  }

  // parsed[0] = pA  — [x, y] as hex or decimal strings
  // parsed[1] = pB  — [[x1,y1],[x2,y2]] as hex or decimal strings
  // parsed[2] = pC  — [x, y] as hex or decimal strings
  // parsed[3] = pubSignals — [s0, s1, s2, ...] as decimal strings
  if (!parsed[0] || !parsed[1] || !parsed[2] || !parsed[3]) {
    throw new Error("Unexpected calldata structure from snarkjs");
  }

  // Ensure values are strings for ethers.js contract encoding
  const ensureString = (val) => {
    if (typeof val === "string") return val;
    if (typeof val === "number") return val.toString();
    if (typeof val === "bigint") return val.toString();
    return String(val);
  };

  return {
    pA: parsed[0].map(ensureString),
    pB: parsed[1].map((row) => row.map(ensureString)),
    pC: parsed[2].map(ensureString),
    pubSignals: parsed[3].map(ensureString),
  };
}

/**
 * Debug helper to show what will be sent to the contract.
 */
function debugProofData(pA, pB, pC, pubSignals, publicSignals) {
  console.log("\n[DEBUG] Proof data that will be sent to contract:");
  console.log("  pA (G1 point) =", pA);
  console.log("  pB (G2 point) =", pB);
  console.log("  pC (G1 point) =", pC);
  console.log("  pubSignals (array passed to verifyProof) =", pubSignals);
  console.log("\n[DEBUG] Original publicSignals from proof:");
  publicSignals.forEach((sig, i) => {
    console.log(`    [${i}] = ${sig}`);
  });
  console.log(`\n[DEBUG] Note: Oracle.sol expects uint[3] pubSignals.`);
  console.log(`       Current length: ${pubSignals.length}`);
  if (pubSignals.length !== 3) {
    console.log(`       WARNING: Expected 3 signals, got ${pubSignals.length}!`);
  }
}

// ── CLI Mode ──────────────────────────────────────────────────────────────────
// Run directly: node scripts/generateProof.js --prediction 750 --salt 123 --threshold 500
//
// Example output:
//   [ZK] Public input: threshold=500 bps
//   [ZK] Proof generated successfully
//   ...
//   Solidity pA: ["0x...", "0x..."]
//   ...
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);

  const getArg = (name, defaultVal) => {
    const idx = args.indexOf(`--${name}`);
    if (idx !== -1 && args[idx + 1] !== undefined) {
      return parseInt(args[idx + 1], 10);
    }
    return defaultVal;
  };

  const rawPrediction = getArg("prediction", 750);
  const salt          = getArg("salt", Math.floor(Math.random() * 1e12));
  const threshold     = getArg("threshold", 500);

  console.log("ZK Proof Generator — PredictionProof Circuit");
  console.log("═".repeat(50));

  generateProof({ rawPrediction, salt, threshold })
    .then(({ publicSignals, solidityCalldata }) => {
      console.log("\n=== Generated Proof ===");
      console.log("Input (private/public):");
      console.log(`  raw_prediction: ${rawPrediction} (hidden)`);
      console.log(`  salt:           ${salt} (hidden)`);
      console.log(`  threshold:      ${threshold} bps (public)`);
      console.log("\nPublic signals (snarkjs output):");
      console.log(`  [0] predicted_yield:    ${publicSignals[0]} bps (${(parseInt(publicSignals[0]) / 100).toFixed(2)}%)`);
      console.log(`  [1] is_above_threshold: ${publicSignals[1]} (${publicSignals[1] === "1" ? "YES ≥" : "NO <"} ${threshold})`);
      console.log(`  [2] threshold:          ${publicSignals[2]} bps`);
      console.log("\nSolidity calldata (for contract call):");
      console.log("  pA:", JSON.stringify(solidityCalldata.pA));
      console.log("  pB:", JSON.stringify(solidityCalldata.pB));
      console.log("  pC:", JSON.stringify(solidityCalldata.pC));
      console.log("  pubSignals:", JSON.stringify(solidityCalldata.pubSignals));
      console.log("\n✓ Off-chain verification: PASSED");
      console.log("✓ Proof is valid and ready to submit to Oracle.sol");
    })
    .catch((err) => {
      console.error("\nProof generation failed:", err.message);
      if (err.message.includes("not found")) {
        console.error("Hint: Run `npm run compile:circuit` first");
      }
      process.exit(1);
    });
}
